name: Sync Subtree

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SuperRepo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.TREE_KEY }}

    - name: Configure Git
      run: |
        git config --global user.name 'GitHubActionsBot'
        git config --global user.email 'SyncBot@github.com' 

    - name: Ensure Subtree Exists
      run: |
        if [ ! -d "$SUBREPO_DIR" ]; then
          git subtree add --prefix=$SUBREPO_DIR $SUBREPO_REMOTE $SUBREPO_BRANCH --squash
        fi
      env:
        SUBREPO_REMOTE: git@github.com:HollyFoxtel/ComponentA.git
        SUBREPO_BRANCH: main
        SUBREPO_DIR: componentA     

    - name: Sync to SubRepo
      env:
        SUBREPO_REMOTE: git@github.com:HollyFoxtel/ComponentA.git
        SUBREPO_BRANCH: main
        SUBREPO_DIR: componentA
      run: |
        BUILD_NUMBER=${{ github.run_number }}
        TRIGGERED_BY=${{ github.actor }}

        git subtree pull --prefix=$SUBREPO_DIR --squash $SUBREPO_REMOTE $SUBREPO_BRANCH -m "Auto-update $BUILD_NUMBER triggered by $TRIGGERED_BY"
        
        SPLIT_COMMIT=$(git subtree split --prefix=$SUBREPO_DIR --rejoin --squash --annotate="split: $SUBREPO_DIR - Build $BUILD_NUMBER triggered by $TRIGGERED_BY")
        
        if [ -n "$SPLIT_COMMIT" ]; then
          git subtree push --prefix=$SUBREPO_DIR $SUBREPO_REMOTE $SUBREPO_BRANCH
        fi

    - name: Push SuperRepo Changes
      run: git push origin main
